[package]
name = "squad_goals"
version = "0.1.0"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest

[dependencies]
# foo = { path = "vendor/foo" }

starknet = ">=1.1.0"

[cairo]
sierra-replace-ids = true

[[target.starknet-contract]]
sierra = true
allowed-libfuncs = false
#allowed-libfuncs-list.name = "experimental"
